unbind -a -T prefix
unbind -a -T root
unbind -a -T copy-mode
unbind -a -T copy-mode-vi
set -g prefix '`'
set -g history-limit 30000
setw -g mouse off
set -g default-shell ${SHELL}
set -g default-terminal "xterm-256color"

set -g mode-keys vi
set -g escape-time 1

bind '`' send-prefix
bind ';' command-prompt
bind r source-file ~/.tmux.conf
bind t choose-tree
bind d detach-client

# kill session under cursor in choose-tree: x
# list sessions: tmux ls
# attach to session: tmux a
# create named session: tmux new -s work

bind Space copy-mode
bind -T copy-mode-vi Escape send -X cancel

bind -T copy-mode-vi k send -X cursor-up
bind -T copy-mode-vi j send -X cursor-down
bind -T copy-mode-vi h send -X cursor-left
bind -T copy-mode-vi l send -X cursor-right

bind -T copy-mode-vi H send -X start-of-line
bind -T copy-mode-vi L send -X end-of-line
bind -T copy-mode-vi J send -X scroll-down
bind -T copy-mode-vi K send -X scroll-up

bind -T copy-mode-vi PgUp send -X halfpage-up
bind -T copy-mode-vi PageDown send -X halfpage-down
bind -T copy-mode-vi C-k send -X halfpage-up
bind -T copy-mode-vi C-j send -X halfpage-down

bind -T copy-mode-vi / send -X search-forward
bind -T copy-mode-vi ? send -X search-backward

bind -T copy-mode-vi n send -X search-again
bind -T copy-mode-vi N send -X search-reverse

bind -T copy-mode-vi v  if -F "#{selection_present}" { send -X clear-selection } { send -X begin-selection }
bind -T copy-mode-vi y      send -X copy-selection-no-clear
bind -T copy-mode-vi y      send -X copy-selection-and-cancel

bind -n C-t new-window -c "#{pane_current_path}"
bind -n C-j split-window -v -c "#{pane_current_path}"
bind -n C-k split-window -h -c "#{pane_current_path}"
bind -n C-h prev
bind -n C-l next
bind -n C-n select-pane -t :.+
bind -n C-p select-pane -t :.-
bind -n C-w kill-pane
# bind -n C-q kill-window

set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g status-style bg=blue

